#!/usr/bin/env python3
# -*- coding: utf-8 -*-

### ------------------
### Imports
### ------------------

import os
import sys
import subprocess
import argparse
import time
# Make sure to execute in a terminal if needed
# export PYTHONIOENCODING=UTF-8

def myPrint(string):
    print(string.encode("ascii", "ignore").decode("ascii"))

### ------------------
### Method Definition
### ------------------
def run(params):
    p = subprocess.Popen(params, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return p.wait()

### ------------------
### Main entry point
### ------------------
startTime = time.time()

pwd = os.getcwd()
myPrint('Current directory: ' + pwd)

# Configuration/Default variables
defaultProjectPath = pwd
defaultSourceryPath = pwd + '/../Pods/Sourcery'
defaultSourceryBin = defaultSourceryPath + '/bin/sourcery'
defaultSourceryTemplatesPath = defaultSourceryPath + '/Templates/'
defaultCustomTemplates = defaultProjectPath + '/AutoGenerated/Templates/'
defaultAutoGeneratedPath = defaultProjectPath + '/AutoGenerated/Code'

parser = argparse.ArgumentParser(description = 'Auto Generate code with sourcery')

parser.add_argument('--projectPath',
                    action = 'store',
                    dest = 'projectPath',
                    default = defaultProjectPath,
                    help = 'Project path')

parser.add_argument('--sourceryBin',
                    action = 'store',
                    dest = 'sourceryBin',
                    default = defaultSourceryBin,
                    help = 'Sourcery Binary filepath')

parser.add_argument('--sourceryPath',
                    action = 'store',
                    dest = 'sourceryPath',
                    default = defaultSourceryPath,
                    help = 'Sourcery Path')

parser.add_argument('--sourceryTemplatesPath',
                    action = 'store',
                    dest = 'sourceryTemplatesPath',
                    default = defaultSourceryTemplatesPath,
                    help = 'Sourcery templates path')
 
parser.add_argument('--customTemplates',
                    action = 'store',
                    dest = 'customTemplates',
                    default = defaultCustomTemplates,
                    help = 'Custom templates path')

parser.add_argument('--autoGeneratedPath',
                    action = 'store',
                    dest = 'autoGeneratedPath',
                    default = defaultAutoGeneratedPath,
                    help = 'Path for code generation')

args = parser.parse_args()

# Execute sourcery
sourcery = args.sourceryBin

myPrint('Generating predefined templates')
command1 = args.sourceryBin + ' --sources ' + args.projectPath + ' --templates ' + args.sourceryTemplatesPath + ' --output ' + args.autoGeneratedPath
myPrint('Trying: \n' + command1)
os.system(command1)

myPrint('Generating custom templates')
command2 = args.sourceryBin + ' --sources ' + args.projectPath + ' --templates ' + args.customTemplates + ' --output ' + args.autoGeneratedPath
myPrint('Trying: \n' + command2)
os.system(command2)

endTime = time.time()

runTime = endTime - startTime

myPrint("")
myPrint("Code autogeneration done in %0.1f seconds" % runTime)
myPrint("")

# Build phase example
#"${SRCROOT}"/Autogenerated/autoGenerateCode.py \
#    --projectPath './CarSharing' \
#    --sourceryBin './Pods/Sourcery/bin/sourcery' \
#    --sourceryTemplatesPath './Pods/Sourcery/Templates' \
#    --customTemplates './Autogenerated/Templates' \
#    --autoGeneratedPath './CarSharing/Autogenerated'
