disabled_rules: # rule identifiers to exclude from running
  - control_statement
  - trailing_whitespace
  - class_delegate_protocol
  - weak_delegate
  - unused_closure_parameter
  - switch_case_alignment
  - sorted_imports
  
opt_in_rules: # some rules are only opt-in
  - empty_count
  - multiline_parameters
  - function_parameter_count
  - conditional_returns_on_newline
  - trailing_semicolon
  # Find all the available rules by running:
  # swiftlint rules

included:
  - ../SharedUtils
  - ../SharedUtilsTests


# CONFIGURATION
empty_count:
    severity: error
    
shorthand_operator:
    severity: error

force_cast:
   severity: error
   
force_try:
  severity: error

line_length:
  warning: 120
  error: 160

function_body_length:
  warning: 200
  error: 250

type_body_length:
  warning: 250
  error: 300

file_length:
  warning: 350
  error: 400

type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded:
    - iPhone
    - T
    - U

identifier_name:
  severity: error
  min_length:
    warning: 3
    error: 2
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - frame
    - rect
    - model
    - row
    - hud
    - key
    - url
    - day
    - pin
    - map
    - red
    - tag
    - lhs
    - rhs
    - nib
    - rx
    - brl
    - inr
    - myr
    - php
    - ext
    - vc
    - nc
    - iv
    - x
    - y
    
# multiline_parameters: warning
function_parameter_count:
    warning: 5
    error: 6

cyclomatic_complexity:
    warning: 50
    error: 61

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
